line-length = 88
indent-width = 4
target-version = "py310"

# Enable flake8-import-order
select = ["E", "F", "I"]

# Sort imports
src = ["src", "tests"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[per-file-ignores]
"__init__.py" = ["F401"]

[isort]
force-single-line = true
known-first-party = ["myproject"]
known-third-party = ["pytest"]